### ISSUE TITLE
Add to Buildpack Registry

### ISSUE THREAD

**Issue by dfreilich** [anynines/gitcredentials#5]
For easier distribution, can you publish this buildpack to the [Buildpack Registry](https://registry.buildpacks.io/)? I personally found it very useful for our purposes, but it was hard to find, and it may help make it more recognizable. 

Docs for that are here: https://buildpacks.io/docs/buildpack-author-guide/publish-a-buildpack/

**Comment by khaledavarteq** [comment]
@dfreilich We did not mean to ignore your proposal, I must have overlooked an email or I never got one. Anyway, that's a good idea and I'll think we'll do that soon!

**Comment by dfreilich** [comment]
No worries! I appreciate you getting back to me 😄

**Comment by ybykov-a9s** [comment]
@dfreilich I've just registered the buildpack after all it's updates.
https://registry.buildpacks.io/buildpacks/anynines/gitcredentials

Thanks for patience ;-)

This issue is done
